name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install cuda
      run:  sudo apt install nvidia-cuda-toolkit
    - name: configure
      run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON
    - name: build
      run: cmake --build build
    - name: Test
      run: cd build && ctest
